import { AllRoutes } from "./AllRoutes";
import "./App.css";

function App() {
	return (
		<div>
			<AllRoutes />
		</div>
	);
}

export default App;

/*{
      "id": 81,
      "name": "",
      "price": 564,
	  "description":"",
      "discount": "50%",
      "image": "",
      "categories": "womenswestern",
      "reviews": 8987,
      "rating": "4.2",
      "sizes": "S, M, L "
    },
    {
      "id":82 ,
      "name": "",
      "price": 450,
	 "description":"",
      "discount": "32%",
      "image": "",
      "categories": "womenswestern",
      "reviews": 3545,
      "rating": "4.4",
      "sizes": "S, M, L "
    },
    {
      "id": 83,
      "name": "",
      "price": 598,
	  "description":"",
      "discount": "20%",
      "image": "",
      "categories": "womenswestern",
      "reviews": 5457,
      "rating": "4.5",
      "sizes": "S, M, L "
    },
    {
      "id": 84,
      "name": "",
      "price": 675,
	  "description":"",
      "discount": "20%",
      "image": "",
      "categories": "womenswestern",
      "reviews": 9808,
      "rating": "4.6",
      "sizes": "S, M, L "
    },
    {
      "id": 85,
      "name": "",
      "price": 443,
	  "description":"",
      "discount": "50%",
      "image": "",
      "categories": "womenswestern",
      "reviews": 8874,
      "rating": "3.7",
      "sizes": "S, M, L "
    },
    {
      "id": 86,
      "name": "",
      "price": 360,
	  "description":"",
      "discount": "30%",
      "image": "",
      "categories": "womenswestern",
      "reviews": 4584,
      "rating": "4",
      "sizes": "S, M, L "
    },
    {
      "id": 87,
      "name": "",
      "price": 450,
	  "description":"",
      "discount": "20%",
      "image": "",
      "categories": "womenswestern",
      "reviews": 3504,
      "rating": "4.7",
      "sizes": "S, M, L "
    },
    {
      "id": 88,
      "name": "",
      "price": 988,
	  "description":"",
      "discount": "20%",
      "image": "",
      "categories": "womenswestern",
      "reviews": 453,
      "rating": "4.8",
      "sizes": "S, M, L "
    },
    {
      "id": 89,
      "name": "",
      "price": 476,
	  "description":"",
      "discount": "30%",
      "image": "",
      "categories": "womenswestern",
      "reviews": 984,
      "rating": "4.5",
      "sizes": "S, M, L "
    },
    {
      "id": 90,
      "name": "",
      "price": 685,
	  "description":"",
      "discount": "50%",
      "image": "",
      "categories": "womenswestern",
      "reviews": 8474,
      "rating": "4.1",
      "sizes": "S, M, L "
    },
    {
      "id": 91,
      "name": "",
      "price": 340,
	  "description":"",
      "discount": "40%",
      "image": "",
      "categories": "womenswestern",
      "reviews": 324,
      "rating": "4",
      "sizes": "S, M, L "
    },
    {
      "id": 92,
      "name": "",
      "price": 675,
	  "description":"",
      "discount": "20%",
      "image": "",
      "categories": "womenswestern",
      "reviews": 67579,
      "rating": "4.2",
      "sizes": "S, M, L "
    },
    {
      "id": 93,
      "name": "",
      "price": 765,
	  "description":"",
      "discount": "20%",
      "image": "",
      "categories": "womenswestern",
      "reviews": 6546,
      "rating": "4.8",
      "sizes": "S, M, L "
    },
    {
      "id": 94,
      "name": "",
      "price": 890,
	  "description":"",
      "discount": "30%",
      "image": "",
      "categories": "womenswestern",
      "reviews": 7868,
      "rating": "4.5",
      "sizes": "S, M, L "
    },
    {
      "id": 95,
      "name": "",
      "price": 498,
	  "description":"",
      "discount": "50%",
      "image": "",
      "categories": "womenswestern",
      "reviews": 67587,
      "rating": "4.1",
      "sizes": "S, M, L "
    },
    {
      "id": 96 ,
      "name": "",
      "price": 589,
	  "description":"",
      "discount": "30%",
      "image": "",
      "categories": "womenswestern",
      "reviews": 8954,
      "rating": "5",
      "sizes": "S, M, L "
    },
    {
      "id": 97,
      "name": "",
      "price": 850,
	  "description":"",
      "discount": "20%",
      "image": "",
      "categories": "womenswestern",
      "reviews": 7867,
      "rating": "4.2",
      "sizes": "S, M, L "
    },
    {
      "id": 98,
      "name": "",
      "price": 978,
	  "description":"",
      "discount": "20%",
      "image": "",
      "categories": "womenswestern",
      "reviews": 54774,
      "rating": "4.5",
      "sizes": "S, M, L "
    },
    {
      "id": 99,
      "name": "",
      "price": 532,
	  "description":"",
      "discount": "60%",
      "image": "",
      "categories": "womenswestern",
      "reviews": 984879,
      "rating": "4.5",
      "sizes": "S, M, L "
    },
    {
      "id": 100,
      "name": "",
      "price": 786,
	  "description":"",
      "discount": "50%",
      "image": "",
      "categories": "womenswestern",
      "reviews": 87874,
      "rating": "4.1",
      "sizes": "S, M, L "
    },
    {
      "id": 101,
      "name": "",
      "price": 364,
	  "description":"",
      "discount": "30%",
      "image": "",
      "categories": "womenswestern",
      "reviews": 49854,
      "rating": "4",
      "sizes": "S, M, L "
    },
    {
      "id": 102,
      "name": "",
      "price": 643,
	  "description":"",
      "discount": "20%",
      "image": "",
      "categories": "womenswestern",
      "reviews": 76809,
      "rating": "4.2",
      "sizes": "S, M, L "
    },
    {
      "id": 103,
      "name": "",
      "price": 875,
	  "description":"",
      "discount": "20%",
      "image": "",
      "categories": "womenswestern",
      "reviews": 54654,
      "rating": "4.5",
      "sizes": "S, M, L "
    },
    {
      "id": 104,
      "name": "",
      "price": 324,
	  "description":"",
      "discount": "30%",
      "image": "",
      "categories": "womenswestern",
      "reviews": 98498,
      "rating": "4.5",
      "sizes": "S, M, L "
    },
    {
      "id": 105,
      "name": "",
      "price": 467,
      "description":"",
	  "discount": "50%",
      "image": "",
      "categories": "womenswestern",
      "reviews": 87674,
      "rating": "4.1",
      "sizes": "S, M, L "
    },
    {
      "id": 106,
      "name": "",
      "price": 675,
	  "description":"",
      "discount": "50%",
      "image": "",
      "categories": "womenswestern",
      "reviews": 88774,
      "rating": "4.1",
      "sizes": "S, M, L "
    },
    {
      "id": 107,
      "name": "",
      "price": 786,
	  "description":"",
      "discount": "20%",
      "image": "",
      "categories": "womenswestern",
      "reviews": 38754,
      "rating": "4.2",
      "sizes": "S, M, L "
    },
    {
      "id": 108,
      "name": "",
      "price": 580,
	  "description":"",
      "discount": "20%",
      "image": "",
      "categories": "womenswestern",
      "reviews": 676774,
      "rating": "4.5",
      "sizes": "S, M, L "
    },
    {
      "id": 109,
      "name": "",
      "price": 620,
	  "description":"",
      "discount": "30%",
      "image": "",
      "categories": "womenswestern",
      "reviews": 89984,
      "rating": "4.5",
      "sizes": "S, M, L "
    },
    {
      "id": 110,
      "name": "",
      "price": 830,
	  "description":"",
      "discount": "50%",
      "image": "",
      "categories": "womenswestern",
      "reviews": 87674,
      "rating": "4.1",
      "sizes": "S, M, L "
    },
    {
      "id": 111,
      "name": "",
      "price": 3430,
	  "description":"",
      "discount": "50%",
      "image": "",
      "categories": "womenswestern",
      "reviews": 88674,
      "rating": "4.1",
      "sizes": "S, M, L "
    },
    {
      "id": 112,
      "name": "",
      "price": 5770,
	  "description":"",
      "discount": "20%",
      "image": "",
      "categories": "womenswestern",
      "reviews": 389754,
      "rating": "4.2",
      "sizes": "S, M, L "
    },
    {
      "id": 113,
      "name": "",
      "price": 560,
	  "description":"",
      "discount": "20%",
      "image": "",
      "categories": "womenswestern",
      "reviews": 674,
      "rating": "4.5",
      "sizes": "S, M, L "
    },
    {
      "id": 114,
      "name": "",
      "price": 960,
	  "description":"",
      "discount": "30%",
      "image": "",
      "categories": "womenswestern",
      "reviews": 675984,
      "rating": "4.5",
      "sizes": "S, M, L "
    },
    {
      "id": 115,
      "name": "",
      "price": 740,
	  "description":"",
      "discount": "50%",
      "image": "",
      "categories": "womenswestern",
      "reviews": 897874,
      "rating": "4.1",
      "sizes": "S, M, L "
    },
    {
      "id": 116,
      "name": "",
      "price": 450,
	  "description":"",
      "discount": "50%",
      "image": "",
      "categories": "womenswestern",
      "reviews": 874,
      "rating": "4.1",
      "sizes": "S, M, L "
    },
    {
      "id": 117,
      "name": "",
      "price": 800,
	  "description":"",
      "discount": "20%",
      "image": "",
      "categories": "womenswestern",
      "reviews": 35764,
      "rating": "4.2",
      "sizes": "S, M, L "
    },
    {
      "id": 118,
      "name": "",
      "price": 500,
	  "description":"",
      "discount": "20%",
      "image": "",
      "categories": "womenswestern",
      "reviews": 687974,
      "rating": "4.5",
      "sizes": "S, M, L "
    },
    {
      "id": 119,
      "name": "",
      "price": 600,
	  "description":"",
      "discount": "30%",
      "image": "",
      "categories": "womenswestern",
      "reviews": 786984,
      "rating": "4.5",
      "sizes": "S, M, L "
    },
    {
      "id": 120,
      "name": "",
      "price": 430,
	  "description":"",
      "discount": "50%",
      "image": "",
      "categories": "womenswestern",
      "reviews": 8774,
      "rating": "4.1",
      "sizes": "S, M, L "
    },
    {
      "id": 121,
      "name": "",
      "price": 400,
	  "description":"",
      "discount": "50%",
      "image": "",
      "categories": "womenswestern",
      "reviews": 878674,
      "rating": "4.1",
      "sizes": "S, M, L "
    }*/
